"""Canonical event schema + event bus + durable event repository."""

from __future__ import annotations

import asyncio

from fieldpilot.events.bus import InMemoryEventBus, publish_event
from fieldpilot.events.schema import Event, EventType, Severity
from fieldpilot.events.store import SQLiteEventRepository


def make_event(**over) -> Event:
    base = dict(
        worker_id="w-7",
        camera_id="cam-1",
        zone="zone-a",
        event_type=EventType.PPE,
        confidence=0.9,
        severity=Severity.MEDIUM,
        payload={"ppe_item": "helmet", "dedup_key": "helmet"},
    )
    base.update(over)
    return Event(**base)


# --------------------------------------------------------------------------- schema


def test_event_has_all_spec_fields():
    ev = make_event()
    d = ev.model_dump(mode="json")
    for field in ("event_id", "worker_id", "camera_id", "zone", "timestamp",
                  "event_type", "confidence", "severity", "payload", "image_url", "video_url"):
        assert field in d, f"missing spec field: {field}"


def test_event_id_autogenerated_and_unique():
    assert make_event().event_id != make_event().event_id


def test_timestamp_accepts_epoch_and_iso():
    ev = make_event(timestamp=1_700_000_000.0)
    assert ev.timestamp.tzinfo is not None
    ev2 = Event(**ev.model_dump(mode="json"))  # round-trips through JSON
    assert ev2.event_id == ev.event_id


def test_confidence_bounded():
    import pytest
    from pydantic import ValidationError

    with pytest.raises(ValidationError):
        make_event(confidence=1.5)


def test_dedup_key_stable_for_same_issue():
    a = make_event()
    b = make_event()
    assert a.dedup_key() == b.dedup_key() == "ppe:w-7:zone-a:helmet"
    c = make_event(payload={"ppe_item": "vest", "dedup_key": "vest"})
    assert c.dedup_key() != a.dedup_key()


def test_all_spec_event_types_supported():
    for t in ("ppe", "fall", "crack", "measurement", "fire", "gas", "rfi"):
        ev = make_event(event_type=EventType(t))
        assert ev.event_type.value == t


# --------------------------------------------------------------------------- bus


async def test_inmemory_bus_fanout():
    bus = InMemoryEventBus()
    received: list[tuple[str, dict]] = []

    async def handler(topic: str, msg: dict) -> None:
        received.append((topic, msg))

    await bus.subscribe("events.ppe", handler)
    await bus.subscribe("events.all", handler)
    await bus.subscribe("events.fall", handler)  # must NOT fire for a ppe event
    await bus.start()
    try:
        await publish_event(bus, make_event())
        await asyncio.sleep(0.05)
    finally:
        await bus.stop()
    topics = sorted(t for t, _ in received)
    assert topics == ["events.all", "events.ppe"]


async def test_bus_handler_exception_does_not_kill_bus():
    bus = InMemoryEventBus()
    got: list[dict] = []

    async def bad(topic: str, msg: dict) -> None:
        raise RuntimeError("boom")

    async def good(topic: str, msg: dict) -> None:
        got.append(msg)

    await bus.subscribe("events.ppe", bad)
    await bus.subscribe("events.ppe", good)
    await bus.start()
    try:
        await publish_event(bus, make_event())
        await asyncio.sleep(0.05)
    finally:
        await bus.stop()
    assert len(got) == 1


# --------------------------------------------------------------------------- repository


async def test_sqlite_event_repository_roundtrip(tmp_path):
    repo = SQLiteEventRepository(str(tmp_path / "events.db"))
    await repo.start()
    try:
        ev = make_event(zone="zone-b")
        await repo.save_event(ev)
        await repo.save_event(ev)  # idempotent
        rows = await repo.list_events(zone="zone-b")
        assert len(rows) == 1
        assert rows[0]["event_id"] == ev.event_id
        assert rows[0]["payload"]["ppe_item"] == "helmet"
        counts = await repo.count_by_type()
        assert counts == {"ppe": 1}
    finally:
        await repo.stop()


async def test_sqlite_event_repository_filters(tmp_path):
    repo = SQLiteEventRepository(str(tmp_path / "events.db"))
    await repo.start()
    try:
        await repo.save_event(make_event(worker_id="w-1"))
        await repo.save_event(make_event(worker_id="w-2", event_type=EventType.FALL))
        assert len(await repo.list_events(worker_id="w-1")) == 1
        assert len(await repo.list_events(event_type="fall")) == 1
        assert len(await repo.list_events(event_type="crack")) == 0
    finally:
        await repo.stop()
