"""solvePnP head pose: sign convention, gaze cone, and graceful fallback.

Ground truth is generated by *projecting* `HEAD_MODEL_3D_MM` with `cv2.projectPoints` under a known
rotation, so the expected yaw/pitch/roll are exact by construction rather than eyeballed pixels.

Sign convention under test (see fieldpilot/perspective.py):
  yaw   > 0 → head turned toward the image right (increasing pixel x) = the worker's own left
  pitch > 0 → head tilted up (decreasing pixel y)
  roll  > 0 → head tilted clockwise as seen in the image
"""

from __future__ import annotations

import cv2
import numpy as np

from fieldpilot.core.types import (
    KP_LEFT_EAR,
    KP_LEFT_EYE,
    KP_NOSE,
    KP_RIGHT_EAR,
    KP_RIGHT_EYE,
    NUM_KEYPOINTS,
    PersonDetection,
)
from fieldpilot.perspective import (
    HEAD_MODEL_3D_MM,
    HEAD_MODEL_KP_ORDER,
    GazeEstimator,
    rotation_from_euler,
)
from tests.conftest import FRAME_H, FRAME_W, make_cfg

FACE_KPS = (KP_NOSE, KP_LEFT_EYE, KP_RIGHT_EYE, KP_LEFT_EAR, KP_RIGHT_EAR)


def _estimator(**sections) -> GazeEstimator:
    gaze = GazeEstimator(make_cfg(**sections))
    gaze.set_frame_size(FRAME_W, FRAME_H)
    return gaze


def _project_head(
    yaw_deg: float = 0.0,
    pitch_deg: float = 0.0,
    roll_deg: float = 0.0,
    nose_px: tuple[float, float] = (FRAME_W / 2.0, FRAME_H / 2.0),
    depth_mm: float = 900.0,
) -> np.ndarray:
    """2D pixels for the 5 facial keypoints of a head at `nose_px` with the given orientation.

    The nose tip is the model origin, so `tvec` is chosen to land the nose exactly on `nose_px`
    under the same pinhole camera the estimator synthesises (f = frame width, principal point at the
    frame centre).
    """

    f = float(FRAME_W)
    px, py = FRAME_W / 2.0, FRAME_H / 2.0
    cam = np.array([[f, 0.0, px], [0.0, f, py], [0.0, 0.0, 1.0]], dtype=np.float64)
    # nose tip projects to nose_px  ⇒  t = (z/f * (u - px), z/f * (v - py), z)
    tvec = np.array(
        [
            [depth_mm / f * (nose_px[0] - px)],
            [depth_mm / f * (nose_px[1] - py)],
            [depth_mm],
        ],
        dtype=np.float64,
    )
    rvec, _ = cv2.Rodrigues(rotation_from_euler(yaw_deg, pitch_deg, roll_deg))
    pts, _ = cv2.projectPoints(HEAD_MODEL_3D_MM, rvec, tvec, cam, np.zeros((5, 1)))
    return pts.reshape(-1, 2)


def _person(
    track_id: int = 1,
    conf: float = 0.9,
    visible: tuple[int, ...] = FACE_KPS,
    **pose,
) -> PersonDetection:
    """A PersonDetection whose facial keypoints are the exact projection of a known head pose."""

    pts = _project_head(**pose)
    kp = np.zeros((NUM_KEYPOINTS, 3), dtype=np.float32)
    for row, kp_idx in enumerate(HEAD_MODEL_KP_ORDER):
        c = conf if kp_idx in visible else 0.05
        kp[kp_idx] = [pts[row][0], pts[row][1], c]
    x1, y1 = float(pts[:, 0].min() - 40), float(pts[:, 1].min() - 40)
    x2, y2 = float(pts[:, 0].max() + 40), float(pts[:, 1].max() + 160)
    return PersonDetection(track_id=track_id, bbox=(x1, y1, x2, y2), conf=0.9, keypoints=kp)


def _bbox_at(u: float, v: float, size: float = 30.0):
    return (u - size / 2, v - size / 2, u + size / 2, v + size / 2)


# --- pose recovery -------------------------------------------------------------------------------


def test_frontal_face_recovers_zero_yaw_via_solvepnp():
    gaze = _estimator()
    person = _person()
    pose = gaze.head_pose(person)

    assert pose is not None
    assert pose["method"] == "solvepnp"
    assert abs(pose["yaw_deg"]) < 1.0
    assert abs(pose["pitch_deg"]) < 1.0
    assert abs(pose["roll_deg"]) < 1.0
    # last_pose() mirrors head_pose() for the GUI and returns a copy, not the live cache entry.
    reported = gaze.last_pose(person.track_id)
    assert reported == pose
    assert reported is not pose


def test_left_and_right_turns_have_opposing_yaw_signs():
    gaze = _estimator()
    # yaw > 0 = turned toward the image right; the ground-truth angle must come back out.
    right = gaze.head_pose(_person(track_id=1, yaw_deg=30.0))
    left = gaze.head_pose(_person(track_id=2, yaw_deg=-30.0))

    assert right is not None and left is not None
    assert right["method"] == left["method"] == "solvepnp"
    assert right["yaw_deg"] > 0.0 > left["yaw_deg"]
    assert abs(right["yaw_deg"] - 30.0) < 2.0
    assert abs(left["yaw_deg"] + 30.0) < 2.0
    # the pixel geometry backs the convention: turning toward the image right swings the visible
    # eye midpoint left of the nose tip.
    pts = _project_head(yaw_deg=30.0)
    eye_mid_x = (pts[1][0] + pts[2][0]) / 2.0
    assert pts[0][0] > eye_mid_x


def test_pitch_and_roll_round_trip_with_correct_signs():
    gaze = _estimator()
    up = gaze.head_pose(_person(track_id=1, pitch_deg=20.0))
    down = gaze.head_pose(_person(track_id=2, pitch_deg=-20.0))
    clockwise = gaze.head_pose(_person(track_id=3, roll_deg=15.0))

    assert up is not None and down is not None and clockwise is not None
    assert abs(up["pitch_deg"] - 20.0) < 2.0
    assert abs(down["pitch_deg"] + 20.0) < 2.0
    assert abs(clockwise["roll_deg"] - 15.0) < 2.0
    # radians are exposed alongside degrees for consumers that want the raw vector.
    assert abs(up["pitch_rad"] - np.radians(up["pitch_deg"])) < 1e-9


def test_pose_survives_subpixel_keypoint_noise():
    gaze = _estimator()
    person = _person(yaw_deg=25.0)
    rng = np.random.default_rng(7)
    for idx in FACE_KPS:
        person.keypoints[idx, 0] += rng.uniform(-0.5, 0.5)
        person.keypoints[idx, 1] += rng.uniform(-0.5, 0.5)

    pose = gaze.head_pose(person)
    assert pose is not None
    assert pose["method"] == "solvepnp"
    assert abs(pose["yaw_deg"] - 25.0) < 8.0


def test_four_visible_keypoints_still_solve():
    """A worker in three-quarter view loses the far ear; PnP must still run on 4 points."""

    gaze = _estimator()
    person = _person(yaw_deg=35.0, visible=(KP_NOSE, KP_LEFT_EYE, KP_RIGHT_EYE, KP_RIGHT_EAR))
    pose = gaze.head_pose(person)

    assert pose is not None
    assert pose["method"] == "solvepnp"
    assert pose["n_points"] == 4
    assert abs(pose["yaw_deg"] - 35.0) < 3.0


# --- gaze decision -------------------------------------------------------------------------------


def test_worker_facing_hazard_is_looking():
    gaze = _estimator()
    # worker on the left of the frame, head turned toward the image right; hazard sits on that ray.
    nose = (200.0, 240.0)
    person = _person(yaw_deg=25.0, nose_px=nose)
    # 25° to the image right of the nose at f = 640 px → +298 px.
    hazard = _bbox_at(nose[0] + FRAME_W * np.tan(np.radians(25.0)), nose[1])

    assert gaze.looking_at(person, hazard) is True
    assert gaze.last_pose(person.track_id)["method"] == "solvepnp"


def test_hazard_outside_the_cone_is_not_looking():
    gaze = _estimator()
    nose = (120.0, 240.0)
    person = _person(yaw_deg=0.0, nose_px=nose)   # staring straight down the optical axis
    far_right = _bbox_at(620.0, 240.0)            # ~38° off the worker's face ray

    assert gaze.looking_at(person, far_right) is False
    # ...and the same worker does see something on their own ray.
    assert gaze.looking_at(person, _bbox_at(nose[0] + 10.0, nose[1])) is True


def test_pitch_is_accounted_for_vertically():
    gaze = _estimator()
    nose = (320.0, 240.0)
    person = _person(nose_px=nose)  # level head, zero pitch

    # a hazard 300 px above/below the face is ~25° off vertically → outside a 25° cone.
    assert gaze.looking_at(person, _bbox_at(nose[0], nose[1] - 300.0)) is False
    assert gaze.looking_at(person, _bbox_at(nose[0], nose[1] + 300.0)) is False
    # tilting the head up by that much brings the high hazard back inside the cone.
    looking_up = _person(track_id=2, pitch_deg=25.0, nose_px=nose)
    assert gaze.looking_at(looking_up, _bbox_at(nose[0], nose[1] - 300.0)) is True


def test_yaw_toward_the_wrong_side_is_not_looking():
    gaze = _estimator()
    nose = (320.0, 240.0)
    person = _person(yaw_deg=-35.0, nose_px=nose)  # turned toward the image left
    assert gaze.looking_at(person, _bbox_at(nose[0] + 250.0, nose[1])) is False
    assert gaze.looking_at(person, _bbox_at(nose[0] - 250.0, nose[1])) is True


# --- degenerate inputs ---------------------------------------------------------------------------


def test_low_confidence_face_falls_back_and_reports_not_looking():
    gaze = _estimator()
    nose = (320.0, 240.0)
    # only the nose and one eye are confident → too few for PnP, and the heuristic needs a pair.
    person = _person(nose_px=nose, visible=(KP_NOSE, KP_LEFT_EYE))
    hazard = _bbox_at(nose[0] + 20.0, nose[1])

    assert gaze.head_pose(person) is None
    assert gaze.last_pose(person.track_id) is None
    assert gaze.looking_at(person, hazard) is False   # never claim a hazard was seen


def test_missing_nose_yields_no_pose_and_no_gaze():
    gaze = _estimator()
    person = _person(visible=(KP_LEFT_EYE, KP_RIGHT_EYE, KP_LEFT_EAR, KP_RIGHT_EAR))

    assert gaze.head_pose(person) is None
    assert gaze.looking_at(person, _bbox_at(320.0, 240.0)) is False


def test_all_zero_keypoints_do_not_raise():
    gaze = _estimator()
    person = PersonDetection(
        track_id=9,
        bbox=(0.0, 0.0, 10.0, 10.0),
        conf=0.5,
        keypoints=np.zeros((NUM_KEYPOINTS, 3), dtype=np.float32),
    )
    assert gaze.head_pose(person) is None
    assert gaze.looking_at(person, _bbox_at(5.0, 5.0)) is False


def test_degenerate_tiny_face_falls_back_to_heuristic():
    """A face a few pixels wide cannot support a 6-DoF fit, but the yaw ratio still works."""

    gaze = _estimator()
    kp = np.zeros((NUM_KEYPOINTS, 3), dtype=np.float32)
    kp[KP_NOSE] = [302.0, 240.0, 0.9]
    kp[KP_LEFT_EYE] = [303.0, 239.0, 0.9]
    kp[KP_RIGHT_EYE] = [299.0, 239.0, 0.9]
    person = PersonDetection(track_id=3, bbox=(290.0, 230.0, 312.0, 330.0), conf=0.8, keypoints=kp)

    pose = gaze.head_pose(person)
    assert pose is not None
    assert pose["method"] == "heuristic"
    assert pose["yaw_deg"] > 0.0            # nose right of the eye midline → turned image right
    assert gaze.last_pose(3) == pose
    # the fallback still produces a usable decision instead of raising.
    assert isinstance(gaze.looking_at(person, _bbox_at(500.0, 240.0)), bool)


def test_no_frame_size_means_no_pose_rather_than_a_crash():
    gaze = GazeEstimator(make_cfg())          # set_frame_size never called
    person = _person(yaw_deg=20.0)
    assert gaze.camera_matrix() is None
    assert gaze.head_pose(person)["method"] == "heuristic"
    assert gaze.looking_at(person, _bbox_at(400.0, 240.0)) is False


# --- interface / plumbing ------------------------------------------------------------------------


def test_calibrated_intrinsics_override_the_frame_size_guess():
    person = _person(yaw_deg=20.0, nose_px=(200.0, 300.0))

    # A wrong frame size gives a wrong pinhole guess, so the recovered yaw is wrong too.
    wrong = GazeEstimator(make_cfg())
    wrong.set_frame_size(1920, 1080)
    assert abs(wrong.head_pose(person)["yaw_deg"] - 20.0) > 5.0

    # Installing the intrinsics the keypoints were actually projected with fixes it.
    f = float(FRAME_W)
    cam = np.array(
        [[f, 0.0, FRAME_W / 2.0], [0.0, f, FRAME_H / 2.0], [0.0, 0.0, 1.0]], dtype=np.float64
    )
    wrong.set_intrinsics(cam, np.zeros(5))
    assert np.array_equal(wrong.camera_matrix(), cam)
    pose = wrong.head_pose(person)
    assert pose["method"] == "solvepnp"
    assert abs(pose["yaw_deg"] - 20.0) < 2.0


def test_pose_cache_is_bounded():
    gaze = _estimator()
    for tid in range(600):
        gaze.head_pose(_person(track_id=tid, yaw_deg=10.0))
    assert len(gaze._poses) <= 256
    assert len(gaze._pose_sig) <= 4 * 256
    assert gaze.last_pose(599) is not None      # newest survives
    assert gaze.last_pose(0) is None            # oldest evicted


def test_gaze_fn_is_the_bound_looking_at():
    gaze = _estimator()
    fn = gaze.gaze_fn()
    person = _person(yaw_deg=0.0, nose_px=(320.0, 240.0))
    assert fn(person, _bbox_at(330.0, 240.0)) == gaze.looking_at(person, _bbox_at(330.0, 240.0))


def test_ego_mode_uses_the_optical_axis_proxy():
    gaze = GazeEstimator(make_cfg(app={"perspective": "EGO"}))
    gaze.set_frame_size(FRAME_W, FRAME_H)
    blind = _person(visible=())                 # no face needed in EGO mode

    assert gaze.looking_at(blind, _bbox_at(FRAME_W / 2, FRAME_H / 2)) is True
    assert gaze.looking_at(blind, _bbox_at(FRAME_W - 5, FRAME_H - 5)) is False
    # an IMU yaw shifts the cone off the optical axis.
    gaze.set_orientation(28.0)
    assert gaze.looking_at(blind, _bbox_at(FRAME_W / 2, FRAME_H / 2)) is False
    assert gaze.looking_at(blind, _bbox_at(FRAME_W - 40, FRAME_H / 2)) is True


def test_both_mode_ors_the_two_perspectives():
    gaze = GazeEstimator(make_cfg(app={"perspective": "BOTH"}))
    gaze.set_frame_size(FRAME_W, FRAME_H)
    # worker in the corner looking away, hazard dead centre → EGO alone carries the decision.
    person = _person(yaw_deg=-40.0, nose_px=(600.0, 440.0))
    assert gaze.looking_at(person, _bbox_at(FRAME_W / 2, FRAME_H / 2)) is True
