"use client";

import { useState } from "react";
import Link from "next/link";
import { PageHeader } from "@/components/PageHeader";
import {
  Badge,
  Button,
  Card,
  Empty,
  ErrorState,
  LiveChip,
  Loading,
  Note,
  SectionTitle,
  Td,
  Th,
  type Tone,
} from "@/components/ui";
import {
  api,
  errorMessage,
  timeAgo,
  type Inspection,
  type NotificationItem,
  type RFI,
  type RFIStatus,
} from "@/lib/api";
import { usePoll } from "@/lib/usePoll";
import { useLiveFeed } from "@/lib/useLiveFeed";

const RFI_TONE: Record<RFIStatus, Tone> = {
  pending_review: "warn",
  approved: "good",
  rejected: "bad",
};

function notificationTone(status: NotificationItem["status"]): Tone {
  if (status === "sent") return "good";
  if (status === "failed") return "bad";
  return "neutral";
}

export default function ActivityPage() {
  const [busy, setBusy] = useState<string | null>(null);
  const [rowError, setRowError] = useState<Record<string, string>>({});

  const live = useLiveFeed({
    topics: ["notification", "rfi", "inspection"],
    onFrame: () => void refresh(),
  });

  const { data, error, loading, refresh } = usePoll(
    async () => {
      const [notes, rfis, insp] = await Promise.all([
        api.notifications(),
        api.rfis({ limit: 20 }),
        api.inspections(),
      ]);
      return { notes, rfis, insp };
    },
    live.connected ? 20000 : 5000,
    [live.connected],
  );

  const complete = async (inspection: Inspection) => {
    setBusy(inspection.inspection_id);
    setRowError((prev) => ({ ...prev, [inspection.inspection_id]: "" }));
    try {
      await api.completeInspection(inspection.inspection_id);
      await refresh();
    } catch (e) {
      setRowError((prev) => ({ ...prev, [inspection.inspection_id]: errorMessage(e) }));
    } finally {
      setBusy(null);
    }
  };

  if (error && !data) {
    return (
      <div className="p-6">
        <PageHeader title="Activity" subtitle="Notifications, RFIs and inspect requests" />
        <ErrorState message={error} onRetry={() => void refresh()} />
      </div>
    );
  }

  if (loading && !data) {
    return (
      <div className="p-6">
        <PageHeader title="Activity" subtitle="Notifications, RFIs and inspect requests" />
        <Card>
          <Loading label="Loading activity…" />
        </Card>
      </div>
    );
  }

  const notifications = data?.notes.notifications ?? [];
  const rfis = data?.rfis.rfis ?? [];
  const inspections = data?.insp.inspections ?? [];

  return (
    <div className="p-6">
      <PageHeader
        title="Activity"
        subtitle="Notifications, RFIs and inspect requests generated by the rules engine"
        action={<LiveChip connected={live.connected} />}
      />

      {error ? (
        <Note tone="warn" title="Showing the last good snapshot">
          {error}
        </Note>
      ) : null}

      <SectionTitle>Notifications</SectionTitle>
      <Card className="overflow-x-auto">
        <table className="w-full min-w-[560px]">
          <thead>
            <tr className="border-b border-line text-left">
              <Th>Channel</Th>
              <Th>Status</Th>
              <Th>Subject</Th>
              <Th>Time</Th>
            </tr>
          </thead>
          <tbody>
            {notifications.length ? (
              notifications.map((n) => (
                <tr key={n.notification_id} className="border-b border-line-soft last:border-0">
                  <Td>
                    <Badge tone="info">{n.channel}</Badge>
                  </Td>
                  <Td>
                    <Badge tone={notificationTone(n.status)}>{n.status}</Badge>
                  </Td>
                  <Td>{n.subject}</Td>
                  <Td>
                    <span className="text-xs text-txt-3">{timeAgo(n.created_at)}</span>
                  </Td>
                </tr>
              ))
            ) : (
              <tr>
                <Td colSpan={4}>
                  <Empty>No notifications yet.</Empty>
                </Td>
              </tr>
            )}
          </tbody>
        </table>
      </Card>

      <div className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-2">
        <div>
          <SectionTitle>RFIs</SectionTitle>
          <Card className="overflow-x-auto">
            <table className="w-full min-w-[420px]">
              <thead>
                <tr className="border-b border-line text-left">
                  <Th>Status</Th>
                  <Th>Title</Th>
                  <Th>Zone</Th>
                </tr>
              </thead>
              <tbody>
                {rfis.length ? (
                  rfis.map((r: RFI) => (
                    <tr key={r.rfi_id} className="border-b border-line-soft last:border-0">
                      <Td>
                        <Badge tone={RFI_TONE[r.status] ?? "neutral"}>
                          {(r.status ?? "").replace("_", " ") || "–"}
                        </Badge>
                      </Td>
                      <Td>
                        <Link href="/rfis" className="text-accent hover:underline">
                          {r.title ?? "Untitled RFI"}
                        </Link>
                      </Td>
                      <Td>
                        <span className="font-mono text-xs text-txt-3">{r.zone ?? "–"}</span>
                      </Td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <Td colSpan={3}>
                      <Empty>No RFIs.</Empty>
                    </Td>
                  </tr>
                )}
              </tbody>
            </table>
          </Card>
        </div>

        <div>
          <SectionTitle>Inspections</SectionTitle>
          <Card className="overflow-x-auto">
            <table className="w-full min-w-[520px]">
              <thead>
                <tr className="border-b border-line text-left">
                  <Th>Priority</Th>
                  <Th>Message</Th>
                  <Th>Status</Th>
                  <Th />
                </tr>
              </thead>
              <tbody>
                {inspections.length ? (
                  inspections.map((i: Inspection) => (
                    <tr key={i.inspection_id} className="border-b border-line-soft last:border-0">
                      <Td>
                        <Badge tone="warn">{i.priority ?? "–"}</Badge>
                      </Td>
                      <Td>
                        {i.message}
                        {i.notes ? (
                          <div className="text-[11px] text-txt-3">{i.notes}</div>
                        ) : null}
                        {rowError[i.inspection_id] ? (
                          <p className="text-[11px] text-red-500" role="alert">
                            {rowError[i.inspection_id]}
                          </p>
                        ) : null}
                      </Td>
                      <Td>
                        <Badge tone={i.status === "completed" ? "good" : "info"}>
                          {i.status ?? "–"}
                        </Badge>
                      </Td>
                      <Td className="text-right">
                        {i.status === "completed" ? null : (
                          <Button
                            size="sm"
                            tone="secondary"
                            disabled={busy === i.inspection_id}
                            onClick={() => void complete(i)}
                            ariaLabel={`Mark inspection ${i.inspection_id} complete`}
                          >
                            {busy === i.inspection_id ? "Saving…" : "Mark done"}
                          </Button>
                        )}
                      </Td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <Td colSpan={4}>
                      <Empty>No inspections.</Empty>
                    </Td>
                  </tr>
                )}
              </tbody>
            </table>
          </Card>
        </div>
      </div>
    </div>
  );
}
