#!/usr/bin/env python
"""Generate a **demonstration** locked validation set under `data/val_set/`.

`LearningService.start_run` refuses to fine-tune until `data/val_set/images/` exists and is
non-empty (`_check_val_set`), because the whole point of the loop is the mAP50 gate and a gate
without a locked val set measures nothing. On a fresh clone that directory is empty, so the gate is
unexercisable end-to-end. This script fills it with obviously-synthetic labelled frames so the
mechanism is runnable and reviewable:

    uv run python scripts/make_val_set.py
    uv run python scripts/make_val_set.py --n 48 --classes "Hardhat,NO-Hardhat"

Layout produced (YOLO detection format, exactly what `build_dataset`'s generated `data.yaml`
points its `val:` key at, and what ultralytics resolves labels for by swapping /images/ → /labels/):

    data/val_set/images/val_000000.jpg   ...
    data/val_set/labels/val_000000.txt   "<cls> <cx> <cy> <w> <h>" normalised, one per object
    data/val_set/README.md               says loudly that this is demo data
    data/val_set/data.yaml               standalone `yolo val` convenience

THIS IS NOT REAL VALIDATION DATA. Drawn rectangles are not hard hats; mAP50 measured on them says
nothing about site performance. Replace it with real labelled frames before trusting any delta —
see the README this script writes.
"""

from __future__ import annotations

import argparse
import json
import random
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "data" / "val_set"
DEMO_MARKER = ".fieldpilot-demo-val-set"

# The 10-class "construction site safety" label space FieldPilot is written against — matches the
# PPE detector `make fetch-models` installs, so a demo gate run measures against the right classes.
DEFAULT_CLASSES = (
    "Hardhat", "Mask", "NO-Hardhat", "NO-Mask", "NO-Safety Vest",
    "Person", "Safety Cone", "Safety Vest", "machinery", "vehicle",
)

IMG_W, IMG_H = 640, 480

README = """\
# data/val_set — SYNTHETIC DEMONSTRATION DATA (not real validation data)

**Everything in this directory was generated by `scripts/make_val_set.py`
(`make val-set-demo`). It is coloured rectangles drawn by OpenCV, not photographs of a
construction site. A mAP50 number measured against it is meaningless as a statement about
real-world safety performance.**

It exists for one reason: `LearningService` blocks a fine-tune run unless `images/` is populated,
so without *something* here the measure-and-gate loop cannot be demonstrated or tested
end-to-end. Treat any delta produced against this set as a check that the *plumbing* works.

## What is here

```
images/   {n} synthetic frames ({w}x{h} JPEG), deterministic for seed {seed}
labels/   one YOLO-format .txt per image: "<class_id> <cx> <cy> <w> <h>", normalised 0-1
data.yaml standalone convenience for `yolo val data=...`
```

Label space ({k} classes):

{class_list}

## Replacing it with a real locked validation set

1. Delete this whole directory (`rm -rf data/val_set`) — do not mix demo frames with real ones,
   and do not leave this README in place once the data is real.
2. Recreate `images/` and `labels/`, then add real frames from your own cameras: representative
   lighting, weather, camera angles, PPE colours and violation cases. A few hundred frames beats
   a few dozen; every class you gate on needs enough instances to move mAP50 at all.
3. Label them in YOLO detection format with **the same class ids, in the same order** as the model
   being fine-tuned (`learning.base_weights` in `config.yaml` — read its `model.names`).
   `fieldpilot/learning/dataset.py` writes the `names:` block straight from those weights.
4. Sanity-check with `yolo val model=<weights> data=data/val_set/data.yaml`.

## Why the real set must be immutable

The gate compares baseline mAP50 against candidate mAP50. That comparison is only meaningful if
both numbers were measured on the *identical* data, so the locked set must never change between
runs, and no frame in it may ever come from the feedback stream — otherwise the model is being
graded on its own homework and "no regression" stops meaning anything. In practice:

- Version the real set (git-lfs, DVC, or an immutable object-store prefix with a recorded hash).
- Make it read-only on disk (`chmod -R a-w data/val_set`) so a stray script cannot edit it.
- If you must change it, treat it as a **new** locked set: every historical mAP50 is now
  incomparable, so record the change and re-measure your baselines.
"""


def _load_class_names(from_model: str | None) -> tuple[list[str], str]:
    """Class names from a checkpoint's own label space, or the built-in default."""

    if from_model:
        path = Path(from_model)
        if path.is_file():
            try:
                from ultralytics import YOLO

                names = YOLO(str(path)).names
                ordered = [str(names[i]) for i in sorted(int(k) for k in names)]
                if ordered:
                    return ordered, f"class names read from {path}"
            except Exception as exc:  # noqa: BLE001 — fall back loudly, do not abort.
                print(f"note: could not read class names from {path} "
                      f"({type(exc).__name__}: {exc}) — using defaults", file=sys.stderr)
        else:
            print(f"note: {path} not present (run `make fetch-models`) — using default classes",
                  file=sys.stderr)
    return list(DEFAULT_CLASSES), "built-in default construction-site-safety class names"


def _palette(k: int) -> list[tuple[int, int, int]]:
    """Distinct-ish BGR colours, one per class, deterministic."""

    base = [
        (60, 200, 250), (200, 90, 60), (70, 70, 220), (140, 200, 90), (200, 60, 200),
        (40, 160, 240), (90, 220, 220), (230, 140, 60), (150, 150, 150), (110, 60, 180),
    ]
    return [base[i % len(base)] for i in range(k)]


def _draw_frame(rng: random.Random, classes: list[str], colours):
    """One synthetic frame + its YOLO label lines. Returns (image, lines)."""

    import cv2
    import numpy as np

    img = np.zeros((IMG_H, IMG_W, 3), dtype=np.uint8)
    # crude "site": graded sky over a flat ground plane, so frames are not uniformly blank.
    for y in range(IMG_H):
        t = y / IMG_H
        img[y, :] = (int(150 + 60 * t), int(130 + 50 * t), int(110 + 30 * t))
    horizon = int(IMG_H * 0.62)
    img[horizon:, :] = (105, 115, 125)
    cv2.line(img, (0, horizon), (IMG_W, horizon), (80, 88, 96), 2)

    lines: list[str] = []
    for _ in range(rng.randint(1, 3)):
        cls = rng.randrange(len(classes))
        bw = rng.randint(70, 190)
        bh = rng.randint(70, 190)
        x1 = rng.randint(8, IMG_W - bw - 8)
        y1 = rng.randint(8, IMG_H - bh - 8)
        x2, y2 = x1 + bw, y1 + bh
        colour = colours[cls]
        if cls % 3 == 0:
            cv2.rectangle(img, (x1, y1), (x2, y2), colour, -1)
        elif cls % 3 == 1:
            cv2.circle(img, ((x1 + x2) // 2, (y1 + y2) // 2), min(bw, bh) // 2, colour, -1)
        else:
            pts = np.array([[(x1 + x2) // 2, y1], [x2, y2], [x1, y2]], dtype=np.int32)
            cv2.fillPoly(img, [pts], colour)
        cv2.rectangle(img, (x1, y1), (x2, y2), (255, 255, 255), 2)
        cv2.putText(img, classes[cls][:16], (x1 + 3, max(14, y1 - 6)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, (255, 255, 255), 1, cv2.LINE_AA)
        lines.append(
            f"{cls} {(x1 + x2) / 2 / IMG_W:.6f} {(y1 + y2) / 2 / IMG_H:.6f} "
            f"{bw / IMG_W:.6f} {bh / IMG_H:.6f}"
        )

    # unmissable watermark: nobody should mistake these frames for site footage.
    cv2.putText(img, "SYNTHETIC DEMO", (18, IMG_H // 2),
                cv2.FONT_HERSHEY_DUPLEX, 1.35, (255, 255, 255), 3, cv2.LINE_AA)
    cv2.putText(img, "NOT REAL VALIDATION DATA", (18, IMG_H // 2 + 40),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2, cv2.LINE_AA)
    return img, lines


def _guard_existing(out: Path, force: bool) -> None:
    """Never silently clobber what might be a real, locked validation set."""

    images = out / "images"
    if not images.is_dir() or not any(images.iterdir()):
        return
    if (out / DEMO_MARKER).is_file() or force:
        return
    raise SystemExit(
        f"refusing to overwrite {out}: it already contains images and carries no "
        f"{DEMO_MARKER} marker, so it may be a REAL locked validation set. A locked set is "
        "meant to be immutable — if you are certain, re-run with --force."
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a synthetic demonstration locked validation set (YOLO format).",
    )
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="output directory")
    parser.add_argument("--n", type=int, default=24, help="number of images (default 24)")
    parser.add_argument(
        "--classes",
        help="comma-separated class names, in class-id order — must match the label space of the "
             "model being fine-tuned",
    )
    parser.add_argument(
        "--from-model", default=str(REPO_ROOT / "models" / "ppe_css.pt"),
        help="read the class names from this checkpoint when --classes is not given",
    )
    parser.add_argument("--seed", type=int, default=1234, help="RNG seed (deterministic output)")
    parser.add_argument("--force", action="store_true", help="overwrite an existing val set")
    args = parser.parse_args(argv)

    if args.n < 1:
        parser.error("--n must be at least 1")

    if args.classes:
        classes = [c.strip() for c in args.classes.split(",") if c.strip()]
        if not classes:
            parser.error("--classes contained no usable names")
        origin = "--classes"
    else:
        classes, origin = _load_class_names(args.from_model)

    import cv2

    out = Path(args.out).expanduser().resolve()
    _guard_existing(out, args.force)

    img_dir, lbl_dir = out / "images", out / "labels"
    for d in (img_dir, lbl_dir):
        if d.exists():
            shutil.rmtree(d)
        d.mkdir(parents=True, exist_ok=True)

    rng = random.Random(args.seed)
    colours = _palette(len(classes))
    objects = 0
    for i in range(args.n):
        img, lines = _draw_frame(rng, classes, colours)
        stem = f"val_{i:06d}"
        if not cv2.imwrite(str(img_dir / f"{stem}.jpg"), img):
            raise SystemExit(f"failed to write {img_dir / f'{stem}.jpg'}")
        (lbl_dir / f"{stem}.txt").write_text("\n".join(lines) + "\n")
        objects += len(lines)

    class_list = "\n".join(f"- `{i}` — {n}" for i, n in enumerate(classes))
    (out / "README.md").write_text(README.format(
        n=args.n, w=IMG_W, h=IMG_H, seed=args.seed, k=len(classes), class_list=class_list,
    ))
    (out / "data.yaml").write_text(
        "# SYNTHETIC DEMO validation set — see README.md. Standalone `yolo val` convenience only;\n"
        "# the learning loop generates its own data.yaml pointing `val:` at this images/ dir.\n"
        f"path: {out}\n"
        "train: images\n"
        "val: images\n"
        "names:\n" + "".join(f"  {i}: {n}\n" for i, n in enumerate(classes))
    )
    (out / DEMO_MARKER).write_text(json.dumps(
        {"generator": "scripts/make_val_set.py", "seed": args.seed, "images": args.n,
         "classes": classes, "synthetic": True}, indent=2) + "\n")

    print(f"wrote {args.n} synthetic frames ({objects} labelled objects) to {out}")
    print(f"  images : {img_dir}")
    print(f"  labels : {lbl_dir}")
    print(f"  classes: {len(classes)} ({origin})")
    print("  NOTE   : demo data — replace with real labelled frames before trusting any mAP50 "
          "delta (see README.md).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
